-- MySQL Script generated by MySQL Workbench
-- Tue Apr  3 18:25:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kip_prepravljen
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `kip_prepravljen` ;

-- -----------------------------------------------------
-- Schema kip_prepravljen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kip_prepravljen` DEFAULT CHARACTER SET utf8 ;
USE `kip_prepravljen` ;

-- -----------------------------------------------------
-- Table `kip_prepravljen`.`DRZAVA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kip_prepravljen`.`DRZAVA` ;

CREATE TABLE IF NOT EXISTS `kip_prepravljen`.`DRZAVA` (
  `ID_DRZAVA` INT NOT NULL AUTO_INCREMENT,
  `NAZIV` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_DRZAVA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kip_prepravljen`.`PISAC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kip_prepravljen`.`PISAC` ;

CREATE TABLE IF NOT EXISTS `kip_prepravljen`.`PISAC` (
  `ID_PISAC` INT NOT NULL AUTO_INCREMENT,
  `IME` VARCHAR(20) NOT NULL,
  `PREZIME` VARCHAR(20) NOT NULL,
  `ID_DRZAVA` INT NOT NULL,
  PRIMARY KEY (`ID_PISAC`),
  INDEX `fk_PISAC_DRZAVA1_idx` (`ID_DRZAVA` ASC),
  CONSTRAINT `fk_PISAC_DRZAVA1`
    FOREIGN KEY (`ID_DRZAVA`)
    REFERENCES `kip_prepravljen`.`DRZAVA` (`ID_DRZAVA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kip_prepravljen`.`IZDAVAC_STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kip_prepravljen`.`IZDAVAC_STATUS` ;

CREATE TABLE IF NOT EXISTS `kip_prepravljen`.`IZDAVAC_STATUS` (
  `ID_IZDAVAC_STATUS` INT NOT NULL AUTO_INCREMENT,
  `STATUS` VARCHAR(50) NOT NULL,
  `OPIS` VARCHAR(250) NULL,
  PRIMARY KEY (`ID_IZDAVAC_STATUS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kip_prepravljen`.`IZDAVAC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kip_prepravljen`.`IZDAVAC` ;

CREATE TABLE IF NOT EXISTS `kip_prepravljen`.`IZDAVAC` (
  `ID_IZDAVAC` INT NOT NULL AUTO_INCREMENT,
  `NAZIV` NVARCHAR(45) NOT NULL,
  `ID_DRZAVA` INT NOT NULL,
  `ID_STATUS` INT NOT NULL,
  PRIMARY KEY (`ID_IZDAVAC`),
  INDEX `fk_IZDAVAC_DRZAVA1_idx` (`ID_DRZAVA` ASC),
  INDEX `fk_IZDAVAC_IZDAVAC_STATUS1_idx` (`ID_STATUS` ASC),
  CONSTRAINT `fk_IZDAVAC_DRZAVA1`
    FOREIGN KEY (`ID_DRZAVA`)
    REFERENCES `kip_prepravljen`.`DRZAVA` (`ID_DRZAVA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IZDAVAC_IZDAVAC_STATUS1`
    FOREIGN KEY (`ID_STATUS`)
    REFERENCES `kip_prepravljen`.`IZDAVAC_STATUS` (`ID_IZDAVAC_STATUS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kip_prepravljen`.`OBLAST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kip_prepravljen`.`OBLAST` ;

CREATE TABLE IF NOT EXISTS `kip_prepravljen`.`OBLAST` (
  `ID_OBLAST` INT NOT NULL AUTO_INCREMENT,
  `NAZIV` VARCHAR(50) NOT NULL,
  `OPIS` VARCHAR(250) NULL,
  PRIMARY KEY (`ID_OBLAST`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kip_prepravljen`.`KNJIGA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kip_prepravljen`.`KNJIGA` ;

CREATE TABLE IF NOT EXISTS `kip_prepravljen`.`KNJIGA` (
  `ID_KNJIGA` INT NOT NULL AUTO_INCREMENT,
  `NASLOV` VARCHAR(50) NOT NULL,
  `ID_OBLAST` INT NOT NULL,
  `NASLOVNICA` VARCHAR(100) NULL,
  PRIMARY KEY (`ID_KNJIGA`),
  INDEX `fk_KNJIGA_KNJIGA_OBLAST1_idx` (`ID_OBLAST` ASC),
  CONSTRAINT `fk_KNJIGA_KNJIGA_OBLAST1`
    FOREIGN KEY (`ID_OBLAST`)
    REFERENCES `kip_prepravljen`.`OBLAST` (`ID_OBLAST`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kip_prepravljen`.`KNJIGA_PISAC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kip_prepravljen`.`KNJIGA_PISAC` ;

CREATE TABLE IF NOT EXISTS `kip_prepravljen`.`KNJIGA_PISAC` (
  `ID_KNJIGA` INT NOT NULL,
  `ID_PISAC` INT NOT NULL,
  INDEX `fk_KNJIGA_PISAC_KNJIGA1_idx` (`ID_KNJIGA` ASC),
  INDEX `fk_KNJIGA_PISAC_PISAC1_idx` (`ID_PISAC` ASC),
  CONSTRAINT `fk_KNJIGA_PISAC_KNJIGA1`
    FOREIGN KEY (`ID_KNJIGA`)
    REFERENCES `kip_prepravljen`.`KNJIGA` (`ID_KNJIGA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KNJIGA_PISAC_PISAC1`
    FOREIGN KEY (`ID_PISAC`)
    REFERENCES `kip_prepravljen`.`PISAC` (`ID_PISAC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kip_prepravljen`.`KNJIGA_IZDAVAC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kip_prepravljen`.`KNJIGA_IZDAVAC` ;

CREATE TABLE IF NOT EXISTS `kip_prepravljen`.`KNJIGA_IZDAVAC` (
  `ID_KNJIGA` INT NOT NULL,
  `ID_IZDAVAC` INT NOT NULL,
  `IZDANJE` INT NOT NULL,
  `GODINA` INT NOT NULL,
  `TIRAZ` INT NOT NULL,
  INDEX `fk_KNJIGA_IZDAVAC_KNJIGA1_idx` (`ID_KNJIGA` ASC),
  INDEX `fk_KNJIGA_IZDAVAC_IZDAVAC1_idx` (`ID_IZDAVAC` ASC),
  CONSTRAINT `fk_KNJIGA_IZDAVAC_KNJIGA1`
    FOREIGN KEY (`ID_KNJIGA`)
    REFERENCES `kip_prepravljen`.`KNJIGA` (`ID_KNJIGA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KNJIGA_IZDAVAC_IZDAVAC1`
    FOREIGN KEY (`ID_IZDAVAC`)
    REFERENCES `kip_prepravljen`.`IZDAVAC` (`ID_IZDAVAC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kip_prepravljen`.`KORISNIK_STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kip_prepravljen`.`KORISNIK_STATUS` ;

CREATE TABLE IF NOT EXISTS `kip_prepravljen`.`KORISNIK_STATUS` (
  `ID_KORISNIK_STATUS` INT NOT NULL AUTO_INCREMENT,
  `NAZIV` VARCHAR(50) NOT NULL,
  `OPIS` VARCHAR(250) NULL,
  PRIMARY KEY (`ID_KORISNIK_STATUS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kip_prepravljen`.`KORISNIK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kip_prepravljen`.`KORISNIK` ;

CREATE TABLE IF NOT EXISTS `kip_prepravljen`.`KORISNIK` (
  `ID_KORISNIK` INT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `POSLEDNJE_LOGOVANJE` DATETIME NULL,
  `ID_STATUS` INT NOT NULL,
  PRIMARY KEY (`ID_KORISNIK`),
  INDEX `fk_KORISNIK_KORISNIK_STATUS1_idx` (`ID_STATUS` ASC),
  CONSTRAINT `fk_KORISNIK_KORISNIK_STATUS1`
    FOREIGN KEY (`ID_STATUS`)
    REFERENCES `kip_prepravljen`.`KORISNIK_STATUS` (`ID_KORISNIK_STATUS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
